require("settings.options")
require("settings.lsp")
require("settings.case_conversion")
require("settings.parse_jwt")
require("settings.keymaps")
require("settings.lazy")
require("settings.color_scheme")
